import "~/styles/globals.css";

import {ClerkProvider} from "@clerk/nextjs";

import { type Metadata } from "next";
import { Inter } from "next/font/google";
import { TopNav } from "./_components/topnav";

export const metadata: Metadata = {
  title: "T3 Gallery",
  description: "Generated by Rinalda",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" >
        <body className={'font-sans ${inter.variable} flex flex-col gap-4'}>
          <TopNav />  
          {children} 
        </body>
      </html>
    </ClerkProvider>
  );
}
